version: '3'
services:
  dashboard-server:
    image: zellesdocker/remote-server
    ports:
      - "8888:8888"
  remote-dashboard:
    build: zellesdocker/remote-dashboard
    ports:
      - "80:80"
