version: '2'
services:
  dashboard-server:
    image: zellesdocker/remote-server
    ports:
      - "8888:8888"
  remote-dashboard:
    image: zellesdocker/remote-dashboard
    ports:
      - "9999:80"
